#!/bin/bash
#
# WRT Buildroot Manager tool.
#

set -e

test -d "$WRT_BUILDROOT_DIR" || { echo "Cannot find wrt-buildroot-manager directory! Did you source 'wrt-buildroot-manager.source'?" ; exit 1 ; }
test -d "$WRT_BUILDROOT_TEMPLATE" || { echo "Cannot find Template directory! Did you source 'wrt-buildroot-manager.source'?" ; exit 1 ; }

source "$WRT_BUILDROOT_DIR"/rules.source

#
# Check project
#
function validate_project_file() {
	test -e "$PROJECT_FILE"  || { echo "Cannot find $PROJECT_FILE in current directory." ; exit 1 ; }
}

#
# Check sane settings
#
function validate_project_settings() {
  test -z "$CUSTOM_OPENWRT_GIT" && { echo "Missing \$CUSTOM_OPENWRT_GIT"; exit 1; }
  test -z "$CUSTOM_OPENWRT_GIT_BRANCH" && { echo "Missing \$CUSTOM_OPENWRT_GIT_BRANCH"; exit 1; }
	true
}

#
# Create a project in the specified directory.
#
# $1    Destination directory; created if it does not exist.
# $2    template=directory option for post merging local overrides
#
function do_create() {
  DEST="$1"
	test -z "$1" && { echo "Missing destination argument."; exit 1; }
  mkdir -p "$DEST"
  cd "$DEST"
  cp -v "$WRT_BUILDROOT_TEMPLATE"/* .

  TEMPLATE="${2##template=}"
  test -z "$TEMPLATE" || test -d "$TEMPLATE" || { echo "Warning: local Template directory not found! Not merging local overrides."; }

  # Initially, do a dumb merge:  just copy user template over the top.
  test -d "$TEMPLATE" && cp -v "$TEMPLATE"/* .

  # Rename special files
  mv -v dot.gitignore .gitignore

  # Now by default create a git repository
  # If one exists, script should die because of `set -e`

	echo "Project created `date`" > README.md

	git init
  git add -A
  git commit -m "Initial."
}

#
# Clone OpenWRT if not already cloned.
# Silently ignore if directory exists even if it is not a git repository (assume user knows what they are doing)
#
function do_clone_openwrt() {
	if ! test -d "$OPENWRT_ROOT" ; then
	  git clone "$CUSTOM_OPENWRT_GIT" "$OPENWRT_ROOT"
	  (cd "$OPENWRT_ROOT" && git checkout "$CUSTOM_OPENWRT_GIT_BRANCH")
  fi
}

#
# Setup package feeds.
# If no CUSTOM_FEEDS exists, will use OpenWRT defaults
# Assumes packages have no spaces in names
#
function do_feeds() {
  if ! test -e .feeds.stamp ; then
    test -e "$CUSTOM_FEEDS" && cp "$CUSTOM_FEEDS" "$OPENWRT_ROOT"/feeds.conf
    ( cd "$OPENWRT_ROOT" && scripts/feeds update )
    ( cd "$OPENWRT_ROOT" && test -e "$CUSTOM_PACKAGES" && scripts/feeds install `cat "$CUSTOM_PACKAGES"` ) || true
    touch .feeds.stamp
  fi
}

#
# Prepare project dot.config
#
function do_config() {
  if ! test -e .config.stamp ; then
    test -e "$CUSTOM_CONFIG" && cp "$CUSTOM_CONFIG" "$OPENWRT_ROOT"/.config
    ( cd "$OPENWRT_ROOT" && make defconfig )
    cp "$OPENWRT_ROOT"/.config .config.cache
    touch .config.stamp
  fi
}

#
# Make the world
#
function do_world() {
  cd "$OPENWRT_ROOT" && make ${CUSTOM_MAKE_CONCURRENCY:+-j$CUSTOM_MAKE_CONCURRENCY}
}

#
# Build a project in the current directory.
#
# This _could_ have been done using Makefiles. But the intention is to really be a straight-line process.
# OpenWRT itself uses Makefiles and we leverage that when needed.
# Also I would like to make this file understandable to a casual user.
#
function do_build() {
  DIR=`pwd`

	validate_project_file
  source "$PROJECT_FILE" && validate_project_settings

  do_clone_openwrt
  do_feeds
  do_config
	do_world
}

#
# Clean files causing a complete rebuild
#
function do_clean() {
  DIR=`pwd`

	validate_project_file
  source "$PROJECT_FILE" && validate_project_settings

	rm -fv .feeds.stamp .config.stamp \
		 "$OPENWRT_ROOT"/feeds.conf "$OPENWRT_ROOT"/.config "$OPENWRT_ROOT"/.config.old
}

#
# Main command logic.
#

VERB="$1"

case "$VERB" in
create)
  shift
  do_create "${@}"
  ;;

build)
  shift
  do_build "${@}"
  ;;

clean)
  shift
  do_clean "${@}"
  ;;

*)
	cat <<EOF
wrt-project create path/to/directory
wrt-project build
wrt-project clean
wrt-project distclean
EOF
  ;;

esac

